# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('quantidade_de_devs', models.CharField(max_length=15)),
            ],
        ),
    ]
